version: "3.7"

services:
  flask:
    build: ./server
    container_name: flask
    restart: always
    environment:
      - APP_NAME=VerificationBackend
      - AWS_ACCESS_KEY_ID='testkey'
      - ENVIRON='DEVELOPMENT'
      - AWS_SECRET_ACCESS_KEY='testsecret'
    ports:
      - "5000:5000"
